

name: Shopping Cart Webstore

on:
  push:
    branches:
    # - master
    - develop
    - feature/hello-world

env:
  GITHUB_NODE_VERSION: 15.4.0

jobs:

  analysis:
    runs-on: ubuntu-latest
    name: analysis testing
    strategy:
      matrix:
        node-version: '15.4.0'
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependency
      run: cd sc-webstore && npm install
    - name: code analysis
      run: cd sc-webstore && npm run lint

  unittest:
    runs-on: ubuntu-latest
    name: unittest testing
    strategy:
      matrix:
        node-version: '15.4.0'
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependency
      run: cd sc-webstore && npm install
    - name: run unittest
      run: cd sc-webstore && npm run test
